Repository thoth-station/prescriptions, pull requests merged in 2021-09, with the labels that each got.

#2863 💊 Contributors Security Scorecards update for 'interrogate'
  prescriptions/in_/interrogate/security_scorecards_contributors.yaml
Labels: size/S

#2864 💊 Packaging Security Scorecards update for 'interrogate'
  prescriptions/in_/interrogate/security_scorecards_packaging.yaml
Labels: size/S

#2865 💊 Signed-Tags Security Scorecards update for 'interrogate'
  prescriptions/in_/interrogate/security_scorecards_signed_tags.yaml
Labels: size/S

#2866 💊 Fuzzing Security Scorecards update for 'intel-tensorflow'
  prescriptions/in_/intel-tensorflow/security_scorecards_fuzzing.yaml
Labels: size/S

#2867 💊 CII-Best-Practices Security Scorecards update for 'intel-tensorflow'
  prescriptions/in_/intel-tensorflow/security_scorecards_cii_best_practices.yaml
Labels: size/S

#2868 💊 Packaging Security Scorecards update for 'intel-tensorflow'
  prescriptions/in_/intel-tensorflow/security_scorecards_packaging.yaml
Labels: size/S

#2869 💊 Automatic-Dependency-Update Security Scorecards update for 'injector'
  prescriptions/in_/injector/score_cards_automatic_dependency_update.yaml
Labels: size/S

#2874 💊 SAST Security Scorecards update for 'injector'
  prescriptions/in_/injector/security_scorecards_sast.yaml
Labels: size/S

#2876 💊 Security-Policy Security Scorecards update for 'inflection'
  prescriptions/in_/inflection/security_scorecards_security_policy.yaml
Labels: size/S

#2877 💊 Packaging Security Scorecards update for 'inflection'
  prescriptions/in_/inflection/security_scorecards_packaging.yaml
Labels: size/S

#2862 💊 Pinned-Dependencies Security Scorecards update for 'interrogate'
  prescriptions/in_/interrogate/security_scorecards_pinned_dependencies.yaml
Labels: size/S

#2870 💊 Token-Permissions Security Scorecards update for 'injector'
  prescriptions/in_/injector/security_scorecards_token_permissions.yaml
Labels: size/S

#6664 💊 Project 'pyobjc-framework-photosui' hosts release notes on GitHub
  prescriptions/py_/pyobjc-framework-photosui/gh_release_notes.yaml
Labels: size/S

#11216 💊 Automatic-Dependency-Update Security Scorecards update for 'sanic'
  prescriptions/sa_/sanic/score_cards_automatic_dependency_update.yaml
Labels: size/S

#17405 💊 Project 'fysom' is a fork on GitHub
  prescriptions/fy_/fysom/gh_forked.yaml
Labels: size/S

#17406 💊 Project 'frozendict' is a fork on GitHub
  prescriptions/fr_/frozendict/gh_forked.yaml
Labels: size/S

#17408 💊 Project 'fpdf2' is a fork on GitHub
  prescriptions/fp_/fpdf2/gh_forked.yaml
Labels: size/S

#17506 💊 Project 'rusty-rlp' was not updated for more than 365 days
  prescriptions/ru_/rusty-rlp/gh_updated.yaml
Labels: size/S

#17210 Stop releasing prescriptions as a container image
  .aicoe-ci.yaml
  .s2i/bin/assemble
  .s2i/bin/environment
  app.py
  requirements.txt
Labels: size/M, approved

#18508 setup version string for kebechet managers
  version.py
Labels: kind/bug, size/XS, approved
