Repository thoth-station/prescriptions, pull requests merged in 2021-11, with the labels that each got.

#18542 Use an https URL in pre-commit references
  .pre-commit-config.yaml
Labels: kind/bug, size/XS, approved

#18541 Move release notes to justification section
  prescriptions/ne_/networkx/release_notes.yaml
Labels: lgtm, size/XS, approved

#18536 Stop resolution if recommending secure software and runtime environment has a CVE
  prescriptions/_containers/ps_cv_ocr/quay_security.yaml
  prescriptions/_containers/ps_cv_pytorch/quay_security.yaml
  prescriptions/_containers/ps_cv_tensorflow/quay_security.yaml
  prescriptions/_containers/ps_ip_ifd/quay_security.yaml
  prescriptions/_containers/ps_nlp/quay_security.yaml
  prescriptions/_containers/ps_nlp_pytorch/quay_security.yaml
  prescriptions/_containers/ps_nlp_tensorflow/quay_security.yaml
  prescriptions/_containers/quay_security.yaml
  prescriptions/_containers/s2i_custom_notebook/quay_security.yaml
  prescriptions/_containers/s2i_custom_py38_notebook/quay_security.yaml
  prescriptions/_containers/s2i_elyra_custom_notebook/quay_security.yaml
  prescriptions/_containers/s2i_generic_data_science_notebook/quay_security.yaml
  prescriptions/_containers/s2i_jupyterbook/quay_security.yaml
  prescriptions/_containers/s2i_lab_elyra/quay_security.yaml
  prescriptions/_containers/s2i_minimal_notebook/quay_security.yaml
  prescriptions/_containers/s2i_minimal_py38_notebook/quay_security.yaml
  prescriptions/_containers/s2i_pytorch_notebook/quay_security.yaml
  prescriptions/_containers/s2i_scipy_notebook/quay_security.yaml
  prescriptions/_containers/s2i_tensorflow_notebook/quay_security.yaml
  prescriptions/_containers/s2i_thoth_dev/quay_security.yaml
  prescriptions/_containers/s2i_thoth_ubi8_py36/quay_security.yaml
  prescriptions/_containers/s2i_thoth_ubi8_py38/quay_security.yaml
  prescriptions/_containers/s2i_thoth_ubi8_py39/quay_security.yaml
Labels: size/XXL, approved

#17211 Produce warnings when exec and eval are used
  prescriptions/_security_warnings/builtins.yaml
Labels: size/S, approved

#18600 💊 Security info update for 'ps-cv-ocr' based on Quay.io scanners
  prescriptions/_containers/ps_cv_ocr/quay_security.yaml
Labels: bot, size/XL, approved

#18601 💊 Security info update for 'ps-cv-pytorch' based on Quay.io scanners
  prescriptions/_containers/ps_cv_pytorch/quay_security.yaml
Labels: bot, size/XL, approved

#18602 💊 Security info update for 'ps-cv-tensorflow' based on Quay.io scanners
  prescriptions/_containers/ps_cv_tensorflow/quay_security.yaml
Labels: bot, size/XL, approved

#18603 💊 Security info update for 'ps-ip-ifd' based on Quay.io scanners
  prescriptions/_containers/ps_ip_ifd/quay_security.yaml
Labels: bot, size/XL, approved

#18604 💊 Security info update for 'ps-nlp' based on Quay.io scanners
  prescriptions/_containers/ps_nlp/quay_security.yaml
Labels: bot, size/XXL, approved

#18605 💊 Security info update for 'ps-nlp-pytorch' based on Quay.io scanners
  prescriptions/_containers/ps_nlp_pytorch/quay_security.yaml
Labels: bot, size/XXL, approved

#18606 💊 Security info update for 'ps-nlp-tensorflow' based on Quay.io scanners
  prescriptions/_containers/ps_nlp_tensorflow/quay_security.yaml
Labels: bot, size/XXL, approved

#18607 💊 Security info update for 's2i-custom-notebook' based on Quay.io scanners
  prescriptions/_containers/s2i_custom_notebook/quay_security.yaml
Labels: bot, size/XXL, approved

#18608 💊 Security info update for 's2i-custom-py38-notebook' based on Quay.io scanners
  prescriptions/_containers/s2i_custom_py38_notebook/quay_security.yaml
Labels: bot, size/XXL, approved

#18609 💊 Security info update for 's2i-elyra-custom-notebook' based on Quay.io scanners
  prescriptions/_containers/s2i_elyra_custom_notebook/quay_security.yaml
Labels: bot, size/XXL, approved

#18610 💊 Security info update for 's2i-generic-data-science-notebook' based on Quay.io scanners
  prescriptions/_containers/s2i_generic_data_science_notebook/quay_security.yaml
Labels: bot, size/XXL, approved

#18611 💊 Security info update for 's2i-jupyterbook' based on Quay.io scanners
  prescriptions/_containers/s2i_jupyterbook/quay_security.yaml
Labels: bot, size/L, approved

#18612 💊 Security info update for 's2i-lab-elyra' based on Quay.io scanners
  prescriptions/_containers/s2i_lab_elyra/quay_security.yaml
Labels: bot, size/XXL, approved

#18613 💊 Security info update for 's2i-minimal-notebook' based on Quay.io scanners
  prescriptions/_containers/s2i_minimal_notebook/quay_security.yaml
Labels: bot, size/XXL, approved

#18614 💊 Security info update for 's2i-minimal-py38-notebook' based on Quay.io scanners
  prescriptions/_containers/s2i_minimal_py38_notebook/quay_security.yaml
Labels: bot, size/XXL, approved

#18615 💊 Security info update for 's2i-pytorch-notebook' based on Quay.io scanners
  prescriptions/_containers/s2i_pytorch_notebook/quay_security.yaml
Labels: bot, size/XXL, approved

#18616 💊 Security info update for 's2i-scipy-notebook' based on Quay.io scanners
  prescriptions/_containers/s2i_scipy_notebook/quay_security.yaml
Labels: bot, size/XXL, approved

#18617 💊 Security info update for 's2i-tensorflow-notebook' based on Quay.io scanners
  prescriptions/_containers/s2i_tensorflow_notebook/quay_security.yaml
Labels: bot, size/XXL, approved

#18618 💊 Security info update for 's2i-thoth-dev' based on Quay.io scanners
  prescriptions/_containers/s2i_thoth_dev/quay_security.yaml
Labels: bot, size/L, approved

#18621 💊 Security info update for 's2i-thoth-ubi8-py39' based on Quay.io scanners
  prescriptions/_containers/s2i_thoth_ubi8_py39/quay_security.yaml
Labels: bot, size/XXL, approved

#18544 TensorFlow in versions >=2.6.0,<2.7.0 overpinned Keras dependency
  prescriptions/te_/tensorflow/tf_26_keras27.yaml
Labels: size/M, approved

#18624 Warn about marshal.load and marshal.loads and their security implications
  prescriptions/_security_warnings/marshal.yaml
Labels: size/S, approved

#18623 Recommend using defusedxml to avoid XML specific attacks
  prescriptions/de_/defusedxml/xml_recommend.yaml
Labels: size/M, approved

#18625 Warn when using os.popen() and subprocess.Popen(shell=True)
  prescriptions/_security_warnings/popen.yaml
Labels: size/S, approved

#18629 Link blog post on Red Hat developers
  README.rst
Labels: size/XS, approved
