Repository thoth-station/prescriptions, pull requests merged in 2021-05, with the labels that each got.

#19 Use sieve.SkipPackage sieve in backport sieves
  prescription.yaml
Labels: approved, size/M

#20 update the prow resource limits
  .prow.yaml
Labels: approved, size/XS

#21 fix module name
  prescription.yaml
Labels: approved, ok-to-test, size/XS
