Repository thoth-station/prescriptions, pull requests merged in 2021-12, with the labels that each got.

#18628 Configure prow resources
  .prow.yaml
Labels: size/XS, approved

#18630 Fix link to prescriptions presentation
  README.rst
Labels: size/XS, kind/documentation, approved

#18635 Add my username to approvers
  OWNERS
Labels: size/XS, approved

#18638 Add prescriptions that show container image size of used containers
  prescriptions/_containers/ps_cv_ocr/quay_image_size.yaml
  prescriptions/_containers/ps_cv_pytorch/quay_image_size.yaml
  prescriptions/_containers/ps_cv_tensorflow/quay_image_size.yaml
  prescriptions/_containers/ps_ip_ifd/quay_image_size.yaml
  prescriptions/_containers/ps_nlp/quay_image_size.yaml
  prescriptions/_containers/ps_nlp_pytorch/quay_image_size.yaml
  prescriptions/_containers/ps_nlp_tensorflow/quay_image_size.yaml
  prescriptions/_containers/s2i_custom_notebook/quay_image_size.yaml
  prescriptions/_containers/s2i_custom_py38_notebook/quay_image_size.yaml
  prescriptions/_containers/s2i_elyra_custom_notebook/quay_image_size.yaml
  prescriptions/_containers/s2i_generic_data_science_notebook/quay_image_size.yaml
  prescriptions/_containers/s2i_jupyterbook/quay_image_size.yaml
  prescriptions/_containers/s2i_lab_elyra/quay_image_size.yaml
  prescriptions/_containers/s2i_minimal_f34_py39_notebook/quay_image_size.yaml
  prescriptions/_containers/s2i_minimal_notebook/quay_image_size.yaml
  prescriptions/_containers/s2i_minimal_py38_notebook/quay_image_size.yaml
  prescriptions/_containers/s2i_pytorch_notebook/quay_image_size.yaml
  prescriptions/_containers/s2i_scipy_notebook/quay_image_size.yaml
  prescriptions/_containers/s2i_tensorflow_notebook/quay_image_size.yaml
  prescriptions/_containers/s2i_thoth_dev/quay_image_size.yaml
  prescriptions/_containers/s2i_thoth_f31_py37/quay_image_size.yaml
  prescriptions/_containers/s2i_thoth_f32_py38/quay_image_size.yaml
  prescriptions/_containers/s2i_thoth_f34_py39/quay_image_size.yaml
  prescriptions/_containers/s2i_thoth_ubi8_py36/quay_image_size.yaml
  prescriptions/_containers/s2i_thoth_ubi8_py38/quay_image_size.yaml
  prescriptions/_containers/s2i_thoth_ubi8_py39/quay_image_size.yaml
Labels: size/XXL, approved

#18644 Provide prescriptions that select indexes based on labeled requests
  prescriptions/_indexes/pypi.yaml
  prescriptions/_indexes/pytorch_cpu.yaml
  prescriptions/_indexes/pytorch_cu111.yaml
Labels: size/M, approved

#18647 Avoid clashing label keys when selecting indexes
  prescriptions/_indexes/pypi.yaml
  prescriptions/_indexes/pytorch_cpu.yaml
  prescriptions/_indexes/pytorch_cu111.yaml
Labels: size/S, approved

#18648 Add prescription for selecting or ignoring AICoE TF index
  prescriptions/_indexes/aicoe_avx2.yaml
Labels: size/S, approved

#18649 Use "disabled" instead of "off" as off is boolean in YAML
  prescriptions/_indexes/aicoe_avx2.yaml
  prescriptions/_indexes/pypi.yaml
  prescriptions/_indexes/pytorch_cpu.yaml
  prescriptions/_indexes/pytorch_cu111.yaml
Labels: size/S, approved
