Repository thoth-station/prescriptions, pull requests merged in 2021-08, with the labels that each got.

#99 Warn users if CUDA or cuDNN version is missing when resolving TensorFlow
  prescriptions/te_/tensorflow/tf_cuda_cudnnn.yaml
Labels: size/M

#104 Link docs to TensorFlow Keras if Keras API is used
  prescriptions/te_/tensorflow/tf_keras_docs.yaml
Labels: size/S

#101 Produce warnings if users use unsupported cuDNN and CUDA versions with TensorFlow
  prescriptions/te_/tensorflow/tf_cuda_cudnnn.yaml
Labels: size/M

#103 Warn users if pytest is not in dev-packages
  prescriptions/py_/pytest/no_develop.yaml
Labels: size/S

#110 Use version specifiers for CUDA/cuDNN/Python versions
  prescriptions/_generic/gpu_no_cuda.yaml
  prescriptions/_generic/so_cuda_tags.yaml
  prescriptions/_generic/so_python_36_tags.yaml
  prescriptions/_generic/so_python_37_tags.yaml
  prescriptions/_generic/so_python_38_tags.yaml
  prescriptions/_generic/so_python_39_tags.yaml
  prescriptions/_python36/no_semantic_interpositioning.yaml
  prescriptions/en_/enum34/backport.yaml
  prescriptions/fu_/functools32/backport.yaml
  prescriptions/im_/importlib-metadata/backports.yaml
  prescriptions/im_/importlib-resources/backport.yaml
  prescriptions/mo_/mock/backport.yaml
  prescriptions/pa_/pandas/py36_drop.yaml
  prescriptions/se_/setuptools/py36.yaml
  prescriptions/te_/tensorflow/tf_41827.yaml
  prescriptions/te_/tensorflow/tf_cpu.yaml
  prescriptions/te_/tensorflow/tf_cuda.yaml
  prescriptions/te_/tensorflow/tf_cuda_cudnnn.yaml
  prescriptions/te_/tensorflow/tf_cudnn.yaml
  prescriptions/te_/tensorflow/tf_py.yaml
  prescriptions/to_/torch-model-archiver/cpu_index.yaml
  prescriptions/to_/torch-model-archiver/gpu_index.yaml
  prescriptions/to_/torch-model-archiver/no_cuda.yaml
  prescriptions/to_/torch-model-archiver/no_cuda_match.yaml
  prescriptions/to_/torch-tb-profiler/cpu_index.yaml
  prescriptions/to_/torch-tb-profiler/gpu_index.yaml
  prescriptions/to_/torch/cpu_index.yaml
  prescriptions/to_/torch/gpu_index.yaml
  prescriptions/to_/torchaudio/cpu_index.yaml
  prescriptions/to_/torchaudio/gpu_index.yaml
  prescriptions/to_/torchcsprng/cpu_index.yaml
  prescriptions/to_/torchcsprng/gpu_index.yaml
  prescriptions/to_/torchserve/cpu_index.yaml
  prescriptions/to_/torchserve/gpu_index.yaml
  prescriptions/to_/torchtext/cpu_index.yaml
  prescriptions/to_/torchtext/gpu_index.yaml
  prescriptions/to_/torchvision/cpu_index.yaml
  prescriptions/to_/torchvision/gpu_index.yaml
Labels: size/L, approved

#113 Point users to NEP-19 if they use NumPy's random generator
  prescriptions/nu_/numpy/np_random.yaml
Labels: size/S, approved

#111 Notify if a no longer supported NumPy is used
  prescriptions/nu_/numpy/np_support.yaml
Labels: size/M, approved

#112 Add prescriptions related to supported NumPy's Python version
  prescriptions/nu_/numpy/np_py_support.yaml
Labels: size/M, approved

#68 Warn if no CUDA was detected but tensorflow-gpu is installed
  prescriptions/te_/tensorflow/tf_no_gpu.yaml
Labels: kind/feature, size/S, approved

#80 prescription regarding the pycurl installation with ssl library
  prescriptions/py_/pycurl/ubi8_nss.yaml
Labels: kind/bug, size/M, approved

#114 Correctly skip SciPy accidentally included by TensorFlow
  prescriptions/te_/tensorflow/tf_rm_scipy.yaml
Labels: size/S

#115 Suggest to use tensorflow-gpu for CUDA/cuDNN enabled environments
  prescriptions/te_/tensorflow/tf_gpu.yaml
Labels: size/M

#118 Notify about deprecated parts of the standard library
  prescriptions/_library/deprecated.yaml
Labels: kind/feature, size/S, approved
