Repository thoth-station/prescriptions, pull requests merged in 2022-05, with the labels that each got.

#22741 Fixes in prescriptions to fix schema validation
  prescriptions/is_/iso-639/gh_link.yaml
  prescriptions/is_/iso-639/pypi_release.yaml
  prescriptions/py_/pynvx/gh_release_notes.yaml
Labels: size/XS, approved

#23484 Fix incompatible versions of `black` and `click`
  prescriptions/bl_/black/click8x1x0_black22x1x0.yaml
  prescriptions/bl_/black/click8x1x0_black22x3x0.yaml
Labels: lgtm, size/M, approved

#23483 Add prescription for `tensorflow` and `protobuf==4.21.0-rc1`
  prescriptions/te_/tensorflow/tf_protobuf4210rc1.yaml
Labels: size/S

#23485 Fixes to make prescriptions loadable in adviser
  prescriptions/is_/iso-639/pypi_project_maintainers.yaml
  prescriptions/is_/iso-639/pypi_release.yaml
  prescriptions/py_/pynvx/gh_release_notes.yaml
Labels: size/XS

#23812 Cannot install jinja2 >=2.0,<=2.6 with setuptools >46,==3.0,==3.0.1,==3.0.2
  prescriptions/ji_/jinja2/setuptools46.yaml
Labels: size/S, approved
