Repository thoth-station/prescriptions, pull requests merged in 2022-03, with the labels that each got.

#19496 Advised manifest changes is a list of objects
  prescriptions/in_/intel-tensorflow/omp_num_threads.yaml
  prescriptions/to_/torch/omp_num_threads.yaml
Labels: size/XS

#19748 Cannot install connexion when using markupsafe>=2.1.0
  prescriptions/co_/connexion/markupsafe_210.yaml
Labels: size/M, approved

#20134 Remove prescriptions for old containers
  prescriptions/_containers/s2i_thoth_f31_py37/quay_image_size.yaml
  prescriptions/_containers/s2i_thoth_f31_py37/quay_security.yaml
  prescriptions/_containers/s2i_thoth_f31_py37/quay_security_alternatives.yaml
  prescriptions/_containers/s2i_thoth_f32_py38/quay_image_size.yaml
Labels: size/XXL

#20137 jinja2 >=3.0.0 requires flask <=1.0.0
  prescriptions/ji_/jinja2/flask_100.yaml
Labels: size/M, approved

#20556 Organization must be a string
  prescriptions/py_/pynvx/gh_release_notes.yaml
Labels: size/XS

#20561 Cannot install connexion >=2.4.0,<=2.13.0 with werkzeug <0.14
  prescriptions/_containers/s2i_custom_notebook/quay_security.yaml
  prescriptions/_containers/s2i_minimal_notebook/quay_security.yaml
  prescriptions/_containers/s2i_minimal_py38_notebook/quay_security.yaml
  prescriptions/_containers/s2i_pytorch_notebook/quay_security.yaml
  prescriptions/_containers/s2i_thoth_f31_py37/quay_security.yaml
  prescriptions/_containers/s2i_thoth_ubi8_py36/quay_security.yaml
  prescriptions/_containers/s2i_thoth_ubi8_py38/quay_security.yaml
  prescriptions/co_/connexion/werkzeug1x14_connexion2x4x0.yaml
Labels: size/XXL, approved

#21340 Fix issues in the schema
  prescriptions/_containers/s2i_custom_notebook/quay_security.yaml
  prescriptions/_containers/s2i_minimal_notebook/quay_security.yaml
  prescriptions/_containers/s2i_minimal_py38_notebook/quay_security.yaml
  prescriptions/_containers/s2i_pytorch_notebook/quay_security.yaml
  prescriptions/_containers/s2i_thoth_f31_py37/quay_security.yaml
  prescriptions/_containers/s2i_thoth_ubi8_py36/quay_security.yaml
  prescriptions/_containers/s2i_thoth_ubi8_py38/quay_security.yaml
  prescriptions/py_/pynvx/gh_release_notes.yaml
Labels: size/XXL, approved

#21341 Cannot install click==8.10.0 with black<22.3.0
  prescriptions/bl_/black/click8x10x0_black.yaml
Labels: size/S, approved
