Repository thoth-station/prescriptions, pull requests merged in 2022-08, with the labels that each got.

#26462 Cannot install exceptiongroup >=1.0.0rc8 with hypothesis==6.53.0
  prescriptions/hy_/hypothesis/exceptiongroup_1.0.0rc8.yaml
Labels: size/S, approved

#26463 Update OWNERS
  OWNERS
Labels: lgtm, size/S

#27401 Run pre-commit only on modified files from PR
  .prow.yaml
Labels: size/XS, approved

#27402 Revert "Run pre-commit only on modified files from PR"
  .prow.yaml
Labels: size/XS

#28051 :pill Project 'dj-database-url' has less than 3 maintainers on PyPI
  prescriptions/dj_/dj-database-url/pypi_project_maintainers.yaml
Labels: size/S
